spring.application.name=ventas
server.port=8085

# Configuración de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_cinerama_ventas
spring.datasource.username=postgres
spring.datasource.password=admin

# Hibernate: Crea las tablas automáticamente basado en tu código
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Desactivar la conversión automática de decimales a enteros
spring.jackson.deserialization.accept-float-as-int=false