# Conexión al servidor y perfil
spring.config.import=optional:configserver:http://localhost:8888,optional:file:.env[properties]
spring.profiles.active=dev

spring.application.name=ventas
server.port=8084

# CONFIGURACION DE POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bd_cinerama_ventas
spring.datasource.username=postgres
spring.datasource.password=admin

# HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# CONEXION A EUREKA
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Desactivar la conversión automática de decimales a enteros
spring.jackson.deserialization.accept-float-as-int=false