# config-repo/catalogo-dev.properties
spring.application.name=catalogo
server.port=8082


# Conexi�n a Base de Datos
spring.datasource.url=jdbc:postgresql://postgres:5432/catalogo_db
spring.datasource.username=postgres
spring.datasource.password=admin

# JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# Token de TMDB
tmdb.api.token=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJkNTg0ODI2YWFlYWI2NWEzN2QwNDZkYmIyMjdlMWU5OCIsIm5iZiI6MTc3NjQ0MDg3Mi4xNTkwMDAyLCJzdWIiOiI2OWUyNTYyOGIyMDRiMmM4MDRmMWZiODciLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.v0BTkI53qM26vFXPWqhVJvEFlhn3R0jOOtIHQTuEmG0

# CONEXION A EUREKA
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
eureka.instance.prefer-ip-address=true

