spring.application.name=ventas
server.port=8084

# CONFIGURACION DE POSTGRESQL
spring.datasource.url=jdbc:postgresql://postgres:5432/bd_cinerama_ventas
spring.datasource.username=postgres
spring.datasource.password=admin

# HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# CONEXION A EUREKA
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
eureka.instance.prefer-ip-address=true

# Desactivar la conversi�n autom�tica de decimales a enteros
spring.jackson.deserialization.accept-float-as-int=false