# Config Server / env local
spring.config.import=optional:configserver:http://config-server:8888,optional:file:.env[properties]

# Perfil
spring.profiles.active=dev

# Nombre del microservicio
spring.application.name=cliente


# ===============================
# PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://postgres:5432/microservices_db?currentSchema=schema_cliente
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.properties.hibernate.default_schema=schema_cliente

# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC


# ===============================
# Puerto
# ===============================

server.port=8083


# ===============================
# RENIEC API
# ===============================

reniec.api.url=https://api.json.pe/api/dni
reniec.api.token=19d5888c918568a4982dfc9c39dc0ad52aaddc5c40f06965e1a8ceaafbce


# ===============================
# Actuator
# ===============================

management.endpoints.web.exposure.include=health,info


# ===============================
# Logs
# ===============================

logging.level.hibernate.SQL=OFF
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF

logging.level.root=WARN
logging.level.cinerama=INFO


# ===============================
# Eureka
# ===============================

eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true