spring.config.import=optional:file:.env[.properties]
spring.application.name=cliente 

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/cinerama_cliente
spring.datasource.username=postgres
spring.datasource.password=admin
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

#Puerto del microservicio
server.port=8081

#RENIEC API
reniec.api.url=https://api.json.pe/api/dni
reniec.api.token=${API_TOKEN_RENIEC}

# Actuator
management.endpoints.web.exposure.include=health,info